//! Regression tests for mtx44 text output.
//!
//! A prior writer wrapped each matrix row in its own `{ }`, producing
//! `{ {..}, {..}, {..}, {..} }`. That is not valid ritobin: ritobin's reader (and ours) expects one
//! brace holding 16 bare floats, so the mangled form failed to reparse everywhere, including in the
//! writer's own crate. These tests lock in the canonical flat output and the tolerant read of the
//! legacy form.

use rs_bin::{Bin, BinEntry, BinType, BinValue};
use rs_io::Parse;

fn matrix_bin() -> Bin {
    let mut bin = Bin::new();
    let identity = [
        1.0, 0.0, 0.0, 0.0, //
        0.0, 1.0, 0.0, 0.0, //
        0.0, 0.0, 1.0, 0.0, //
        -10.0, 95.0, 140.0, 1.0,
    ];
    let mut fields = indexmap::IndexMap::new();
    fields.insert(0xe1ad_931bu32, BinValue::Mtx44(identity));
    bin.entries.push(BinEntry {
        path_hash: 0x1234_5678,
        class_hash: 0x9abc_def0,
        fields,
    });
    bin
}

/// The writer must emit the flat 16-float form (no per-row braces), and it must reparse.
#[test]
fn mtx44_text_is_flat_and_roundtrips() {
    let bin = matrix_bin();
    let text = rs_bin::to_text(&bin, None);

    // No per-row wrapper braces: a line inside the matrix must not start with `{`.
    let matrix_body: String = text
        .lines()
        .skip_while(|l| !l.contains("mtx44"))
        .skip(1)
        .take(4)
        .collect::<Vec<_>>()
        .join("\n");
    for line in matrix_body.lines() {
        assert!(
            !line.trim_start().starts_with('{'),
            "matrix row must be bare floats, got: {line:?}\nfull:\n{text}"
        );
    }

    // And it must reparse back to the same matrix.
    let reparsed = rs_bin::from_text(&text, None).expect("flat mtx44 must reparse");
    assert_eq!(
        reparsed.entries[0].fields[&0xe1ad_931bu32],
        bin.entries[0].fields[&0xe1ad_931bu32]
    );
}

/// The legacy per-row-brace form must still be accepted on read, so upgrading does not reject
/// files generated by the old writer. (Re-saving them repairs the format.)
#[test]
fn legacy_per_row_brace_mtx44_is_tolerated() {
    let legacy = r#"#PROP_text
version: u32 = 3
entries: map[hash,embed] = {
    0x12345678 = 0x9abcdef0 {
        0xe1ad931b: mtx44 = {
            { 1, 0, 0, 0 }
            { 0, 1, 0, 0 }
            { 0, 0, 1, 0 }
            { -10, 95, 140, 1 }
        }
    }
}
"#;

    let parsed = rs_bin::from_text(legacy, None).expect("legacy mtx44 must be tolerated");
    let expected = [
        1.0, 0.0, 0.0, 0.0, //
        0.0, 1.0, 0.0, 0.0, //
        0.0, 0.0, 1.0, 0.0, //
        -10.0, 95.0, 140.0, 1.0,
    ];
    match &parsed.entries[0].fields[&0xe1ad_931bu32] {
        BinValue::Mtx44(m) => assert_eq!(*m, expected),
        other => panic!("expected mtx44, got {other:?}"),
    }
}

/// Full loop through the binary format on a real file: bin -> text -> bin must reproduce the matrix.
#[test]
fn real_file_bin_text_bin_roundtrip() {
    let p = r"C:\Users\Frog\Desktop\Projects coding\RubyRe\Mods\Angel Milio\data\characters\milio\skins\skin0.bin";
    let Ok(data) = std::fs::read(p) else {
        eprintln!("skipping: sample file not present");
        return;
    };
    let bin = Bin::from_bytes(&data).expect("parse bin");
    let text = rs_bin::to_text(&bin, None);
    let reparsed = rs_bin::from_text(&text, None).expect("real-file text must reparse");

    // Every mtx44 field must survive the text round-trip byte-for-byte.
    let matrices = |b: &Bin| -> Vec<[f32; 16]> {
        let mut out = Vec::new();
        for e in &b.entries {
            collect_matrices(&BinValue::Embed {
                class: e.class_hash,
                fields: e.fields.clone(),
            }, &mut out);
        }
        out
    };
    assert_eq!(matrices(&bin), matrices(&reparsed));
    let _ = BinType::Mtx44;
}

fn collect_matrices(v: &BinValue, out: &mut Vec<[f32; 16]>) {
    match v {
        BinValue::Mtx44(m) => out.push(*m),
        BinValue::Embed { fields, .. } | BinValue::Pointer { fields, .. } => {
            for f in fields.values() {
                collect_matrices(f, out);
            }
        }
        BinValue::List { items, .. } => {
            for it in items {
                collect_matrices(it, out);
            }
        }
        BinValue::Option { value: Some(inner), .. } => collect_matrices(inner, out),
        BinValue::Map { entries, .. } => {
            for (_, val) in entries {
                collect_matrices(val, out);
            }
        }
        _ => {}
    }
}
